// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropSeekr.Data;

#nullable disable

namespace PropSeekr.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260807080316_AddBrokerLocalityAndBrokerage")]
    partial class AddBrokerLocalityAndBrokerage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropSeekr.Models.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0ef71c1-13ab-4070-9d85-86571adf59c8"),
                            CreatedDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "PBKDF2-SHA256$100000$LVJ7kAGk7zNsEMneVYpBfyC8ZPENOZviao1yEc2gT1s=$hjnNN2d8W2s5SBkDGTAb+ct2M9qD+Csk7rNkZs9hlaM=",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("PropSeekr.Models.Broker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("brokerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrokerageName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("brokerage_name");

                    b.Property<decimal>("ConfirmationComplianceRate")
                        .HasColumnType("numeric")
                        .HasColumnName("confirmation_compliance_rate");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreditBalance")
                        .HasColumnType("integer")
                        .HasColumnName("credit_balance");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<string>("Locality")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("locality");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<decimal?>("ResponseScore")
                        .HasColumnType("numeric")
                        .HasColumnName("response_score");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("VisibilityPenaltyExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visibility_penalty_expires_at");

                    b.Property<bool>("VisibilityPenaltyFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("visibility_penalty_flag");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("brokers");
                });

            modelBuilder.Entity("PropSeekr.Models.BrokerNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BrokerId")
                        .HasColumnType("integer")
                        .HasColumnName("broker_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ChannelStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId", "ReadAt");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("PropSeekr.Models.CreditPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("credit_packs");
                });

            modelBuilder.Entity("PropSeekr.Models.CreditTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer")
                        .HasColumnName("balance_after");

                    b.Property<int>("BrokerId")
                        .HasColumnType("integer")
                        .HasColumnName("broker_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("reference_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId", "CreatedAt");

                    b.ToTable("credit_transactions");
                });

            modelBuilder.Entity("PropSeekr.Models.CreditWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrokerId")
                        .HasColumnType("integer")
                        .HasColumnName("broker_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FreeCreditsBalance")
                        .HasColumnType("integer")
                        .HasColumnName("free_credits_balance");

                    b.Property<DateTime?>("FreeCreditsResetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("free_credits_reset_at");

                    b.Property<int>("PaidCreditsBalance")
                        .HasColumnType("integer")
                        .HasColumnName("paid_credits_balance");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId")
                        .IsUnique();

                    b.ToTable("credit_wallets");
                });

            modelBuilder.Entity("PropSeekr.Models.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DealValue")
                        .HasColumnType("numeric")
                        .HasColumnName("deal_value");

                    b.Property<int>("MarkedByBrokerId")
                        .HasColumnType("integer")
                        .HasColumnName("marked_by_broker_id");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.HasKey("Id");

                    b.HasIndex("MarkedByBrokerId");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("deals");
                });

            modelBuilder.Entity("PropSeekr.Models.Dispute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrokerId")
                        .HasColumnType("integer")
                        .HasColumnName("broker_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResolutionType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("resolution_type");

                    b.Property<int?>("ResolvedAmount")
                        .HasColumnType("integer")
                        .HasColumnName("resolved_amount");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("BrokerId", "Status");

                    b.ToTable("disputes");
                });

            modelBuilder.Entity("PropSeekr.Models.EmailOtpRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RequestIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Email", "Purpose", "IsUsed", "ExpiresAt");

                    b.ToTable("EmailOtpRecords");
                });

            modelBuilder.Entity("PropSeekr.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("listingid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrokerId")
                        .HasColumnType("integer")
                        .HasColumnName("broker_id");

                    b.Property<string>("Configuration")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("configuration");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Facing")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("facing");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("integer")
                        .HasColumnName("floor_number");

                    b.Property<string>("FreshnessCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("freshness_category");

                    b.Property<int?>("FreshnessScore")
                        .HasColumnType("integer")
                        .HasColumnName("freshness_score");

                    b.Property<DateTime?>("FreshnessUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("freshness_updated_at");

                    b.Property<string>("Furnishing")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("furnishing");

                    b.Property<string>("GroupName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("group_name");

                    b.Property<DateTime?>("LastConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_confirmed_at");

                    b.Property<DateTime?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refreshed_at");

                    b.Property<string>("ListingType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("listing_type");

                    b.Property<int?>("MasterId")
                        .HasColumnType("integer")
                        .HasColumnName("master_id");

                    b.Property<DateTime?>("MessageDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("message_datetime");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("PriceStatus")
                        .HasColumnType("text")
                        .HasColumnName("price_status");

                    b.Property<string>("PriceUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("price_unit");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("project_name");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("property_type");

                    b.Property<string>("RawMessageText")
                        .HasColumnType("text")
                        .HasColumnName("raw_message_text");

                    b.Property<string>("RoadInfo")
                        .HasColumnType("text")
                        .HasColumnName("road_info");

                    b.Property<decimal?>("Size")
                        .HasColumnType("numeric")
                        .HasColumnName("size");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.ToTable("listings");
                });

            modelBuilder.Entity("PropSeekr.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("matchid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AiConfidencePct")
                        .HasColumnType("integer")
                        .HasColumnName("ai_confidence_pct");

                    b.Property<string>("AiFlagsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_flags");

                    b.Property<string>("AiReasoning")
                        .HasColumnType("text")
                        .HasColumnName("ai_reasoning");

                    b.Property<string>("AiStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ai_status");

                    b.Property<DateTime?>("AiValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ai_validated_at");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ListingBrokerId")
                        .HasColumnType("integer")
                        .HasColumnName("listing_broker_id");

                    b.Property<int>("ListingId")
                        .HasColumnType("integer")
                        .HasColumnName("listing_id");

                    b.Property<decimal?>("MatchScore")
                        .HasColumnType("numeric")
                        .HasColumnName("match_score");

                    b.Property<string>("MatchTier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("match_tier");

                    b.Property<int>("RequirementBrokerId")
                        .HasColumnType("integer")
                        .HasColumnName("requirement_broker_id");

                    b.Property<int>("RequirementId")
                        .HasColumnType("integer")
                        .HasColumnName("requirement_id");

                    b.Property<string>("ScoreBreakdownJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("score_breakdown");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StatusUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ListingBrokerId");

                    b.HasIndex("ListingId");

                    b.HasIndex("RequirementBrokerId");

                    b.HasIndex("RequirementId");

                    b.HasIndex("State");

                    b.HasIndex("Status");

                    b.ToTable("matches");
                });

            modelBuilder.Entity("PropSeekr.Models.MatchConfirmation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AvailabilityConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("availability_confirmed");

                    b.Property<int>("BrokerId")
                        .HasColumnType("integer")
                        .HasColumnName("broker_id");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<bool?>("PriceNegotiable")
                        .HasColumnType("boolean")
                        .HasColumnName("price_negotiable");

                    b.Property<bool?>("PriceValid")
                        .HasColumnType("boolean")
                        .HasColumnName("price_valid");

                    b.Property<bool?>("ReadyToConnect")
                        .HasColumnType("boolean")
                        .HasColumnName("ready_to_connect");

                    b.Property<DateTime?>("WindowExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_expires_at");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.HasIndex("WindowExpiresAt");

                    b.HasIndex("MatchId", "BrokerId")
                        .IsUnique();

                    b.ToTable("match_confirmations");
                });

            modelBuilder.Entity("PropSeekr.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsContactUnlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("MetaJson")
                        .HasColumnType("text");

                    b.Property<bool>("RequiresTokenUnlock")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TokenCost")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PropSeekr.Models.NotificationPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrokerId")
                        .HasColumnType("integer")
                        .HasColumnName("broker_id");

                    b.Property<bool>("InAppEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("in_app_enabled");

                    b.Property<int>("ReminderFrequencyCapHours")
                        .HasColumnType("integer")
                        .HasColumnName("reminder_frequency_cap_hours");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("WhatsappEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("whatsapp_enabled");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId")
                        .IsUnique();

                    b.ToTable("notification_preferences");
                });

            modelBuilder.Entity("PropSeekr.Models.OtpVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("Id");

                    b.HasIndex("MobileNumber");

                    b.HasIndex("MobileNumber", "OtpCode");

                    b.ToTable("OtpVerifications", (string)null);
                });

            modelBuilder.Entity("PropSeekr.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("BrokerId")
                        .HasColumnType("integer")
                        .HasColumnName("broker_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreditPackId")
                        .HasColumnType("integer")
                        .HasColumnName("credit_pack_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Gateway")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GatewayTxnId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("gateway_txn_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.HasIndex("CreditPackId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("PropSeekr.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountInPaise")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreditsAwarded")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RazorpayOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RazorpayPaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RazorpaySignature")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Receipt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TierId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RazorpayOrderId")
                        .IsUnique();

                    b.HasIndex("Receipt")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("PropSeekr.Models.PropertyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BudgetJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("BudgetMax")
                        .HasColumnType("bigint");

                    b.Property<long?>("BudgetMin")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientPreferencesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreshnessCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FreshnessScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Point>("Location")
                        .HasColumnType("geography (point)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreferredLocationsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyTypesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RadiusKm")
                        .HasColumnType("double precision");

                    b.Property<string>("RequiredAreaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchQueryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UrgencyJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BudgetMax");

                    b.HasIndex("BudgetMin");

                    b.HasIndex("Category");

                    b.HasIndex("ListingType");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("PostedAt")
                        .IsDescending();

                    b.HasIndex("PropertyTypesJson");

                    b.HasIndex("TransactionType");

                    b.HasIndex("UserId");

                    b.HasIndex("City", "Locality");

                    b.ToTable("PropertyRequests");
                });

            modelBuilder.Entity("PropSeekr.Models.Requirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("requirementid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrokerId")
                        .HasColumnType("integer")
                        .HasColumnName("broker_id");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("numeric")
                        .HasColumnName("budget");

                    b.Property<string>("BudgetType")
                        .HasColumnType("text")
                        .HasColumnName("budget_type");

                    b.Property<string>("BudgetUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("budget_unit");

                    b.PrimitiveCollection<string[]>("Configurations")
                        .HasColumnType("text[]")
                        .HasColumnName("configurations");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FacingPref")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("facing_pref");

                    b.Property<string>("FurnishingPref")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("furnishing_pref");

                    b.Property<string>("GroupName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("group_name");

                    b.Property<DateTime?>("MessageDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("message_datetime");

                    b.PrimitiveCollection<int[]>("PreferredLocalityIds")
                        .HasColumnType("integer[]")
                        .HasColumnName("preferred_locality_ids");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("property_type");

                    b.Property<string>("RawMessageText")
                        .HasColumnType("text")
                        .HasColumnName("raw_message_text");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("requirement_type");

                    b.Property<decimal?>("Size")
                        .HasColumnType("numeric")
                        .HasColumnName("size");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.ToTable("requirements");
                });

            modelBuilder.Entity("PropSeekr.Models.Reveal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<DateTime>("RevealedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revealed_at");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("reveals");
                });

            modelBuilder.Entity("PropSeekr.Models.UnlockedProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropertyRequestId");

                    b.HasIndex("UserId", "PropertyRequestId")
                        .IsUnique();

                    b.ToTable("UnlockedProperties");
                });

            modelBuilder.Entity("PropSeekr.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AadharNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("BrokerId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GSTNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMobileVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PanCard")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("ReraRegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AadharNumber")
                        .IsUnique();

                    b.HasIndex("BrokerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.HasIndex("PanCard")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PropSeekr.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MarkedByBrokerId")
                        .HasColumnType("integer")
                        .HasColumnName("marked_by_broker_id");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visit_date");

                    b.HasKey("Id");

                    b.HasIndex("MarkedByBrokerId");

                    b.HasIndex("MatchId");

                    b.ToTable("visits");
                });

            modelBuilder.Entity("PropSeekr.Models.BrokerNotification", b =>
                {
                    b.HasOne("PropSeekr.Models.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("PropSeekr.Models.CreditTransaction", b =>
                {
                    b.HasOne("PropSeekr.Models.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("PropSeekr.Models.CreditWallet", b =>
                {
                    b.HasOne("PropSeekr.Models.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("PropSeekr.Models.Deal", b =>
                {
                    b.HasOne("PropSeekr.Models.Broker", "MarkedByBroker")
                        .WithMany()
                        .HasForeignKey("MarkedByBrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropSeekr.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarkedByBroker");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("PropSeekr.Models.Dispute", b =>
                {
                    b.HasOne("PropSeekr.Models.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropSeekr.Models.CreditTransaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Broker");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("PropSeekr.Models.Listing", b =>
                {
                    b.HasOne("PropSeekr.Models.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("PropSeekr.Models.Match", b =>
                {
                    b.HasOne("PropSeekr.Models.Broker", "ListingBroker")
                        .WithMany()
                        .HasForeignKey("ListingBrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropSeekr.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropSeekr.Models.Broker", "RequirementBroker")
                        .WithMany()
                        .HasForeignKey("RequirementBrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropSeekr.Models.Requirement", "Requirement")
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("ListingBroker");

                    b.Navigation("Requirement");

                    b.Navigation("RequirementBroker");
                });

            modelBuilder.Entity("PropSeekr.Models.MatchConfirmation", b =>
                {
                    b.HasOne("PropSeekr.Models.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropSeekr.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("PropSeekr.Models.Notification", b =>
                {
                    b.HasOne("PropSeekr.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropSeekr.Models.NotificationPreference", b =>
                {
                    b.HasOne("PropSeekr.Models.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("PropSeekr.Models.Payment", b =>
                {
                    b.HasOne("PropSeekr.Models.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropSeekr.Models.CreditPack", "CreditPack")
                        .WithMany()
                        .HasForeignKey("CreditPackId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Broker");

                    b.Navigation("CreditPack");
                });

            modelBuilder.Entity("PropSeekr.Models.PaymentTransaction", b =>
                {
                    b.HasOne("PropSeekr.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropSeekr.Models.PropertyRequest", b =>
                {
                    b.HasOne("PropSeekr.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropSeekr.Models.Requirement", b =>
                {
                    b.HasOne("PropSeekr.Models.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("PropSeekr.Models.Reveal", b =>
                {
                    b.HasOne("PropSeekr.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("PropSeekr.Models.UnlockedProperty", b =>
                {
                    b.HasOne("PropSeekr.Models.PropertyRequest", "PropertyRequest")
                        .WithMany()
                        .HasForeignKey("PropertyRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropSeekr.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropSeekr.Models.User", b =>
                {
                    b.HasOne("PropSeekr.Models.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("PropSeekr.Models.Visit", b =>
                {
                    b.HasOne("PropSeekr.Models.Broker", "MarkedByBroker")
                        .WithMany()
                        .HasForeignKey("MarkedByBrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropSeekr.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarkedByBroker");

                    b.Navigation("Match");
                });
#pragma warning restore 612, 618
        }
    }
}
