using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;
using PropSeekr.Data;

#nullable disable

namespace PropSeekr.Migrations;

/// <summary>
/// Adds business-level connection request state without changing the existing
/// dual-confirmation, reveal, or credit ledger tables.
/// </summary>
[DbContext(typeof(AppDbContext))]
[Migration("20260824000100_AddMatchConnectionRequests")]
public partial class AddMatchConnectionRequests : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS match_connection_requests (
                request_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                match_id integer NOT NULL,
                requesting_broker_id integer NOT NULL,
                receiving_broker_id integer NOT NULL,
                status character varying(30) NOT NULL,
                delivery_channel character varying(20) NOT NULL,
                delivery_status character varying(30) NOT NULL,
                rejection_reason_code character varying(50) NULL,
                rejection_reason_text text NULL,
                created_at timestamp with time zone NOT NULL,
                responded_at timestamp with time zone NULL,
                expires_at timestamp with time zone NOT NULL
            );

            CREATE INDEX IF NOT EXISTS ix_match_connection_requests_match_id_status
                ON match_connection_requests (match_id, status);
            CREATE INDEX IF NOT EXISTS ix_match_connection_requests_receiving_broker_id_status
                ON match_connection_requests (receiving_broker_id, status);

            ALTER TABLE notifications
                ADD COLUMN IF NOT EXISTS connection_request_id bigint NULL;
            CREATE INDEX IF NOT EXISTS ix_notifications_connection_request_id
                ON notifications (connection_request_id);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP INDEX IF EXISTS ix_notifications_connection_request_id;
            ALTER TABLE notifications DROP COLUMN IF EXISTS connection_request_id;
            DROP TABLE IF EXISTS match_connection_requests;
            """);
    }
}
