using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PropSeekr.Data;

#nullable disable

namespace PropSeekr.Migrations;

/// <summary>
/// Adds the durable file-ingestion receipt and the partial unique indexes that
/// the vendored processor's ON CONFLICT clauses require.
/// </summary>
[DbContext(typeof(AppDbContext))]
[Migration("20260830093000_AddFileProcessorTrackingAndDeduplication")]
public partial class AddFileProcessorTrackingAndDeduplication : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS processed_files (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                s3_bucket character varying NOT NULL,
                s3_key character varying NOT NULL,
                listings_inserted integer NULL DEFAULT 0,
                requirements_inserted integer NULL DEFAULT 0,
                brokers_created integer NULL DEFAULT 0,
                localities_created integer NULL DEFAULT 0,
                processed_at timestamp without time zone NULL DEFAULT NOW(),
                CONSTRAINT processed_files_s3_bucket_s3_key_key UNIQUE (s3_bucket, s3_key)
            );

            CREATE UNIQUE INDEX IF NOT EXISTS ux_listings_active_content_hash
                ON listings (content_hash)
                WHERE status = 'ACTIVE' AND content_hash IS NOT NULL;

            CREATE UNIQUE INDEX IF NOT EXISTS ux_requirements_active_content_hash
                ON requirements (content_hash)
                WHERE status = 'ACTIVE' AND content_hash IS NOT NULL;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP INDEX IF EXISTS ux_requirements_active_content_hash;
            DROP INDEX IF EXISTS ux_listings_active_content_hash;
            DROP TABLE IF EXISTS processed_files;
            """);
    }
}
