using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PropSeekr.Data;

#nullable disable

namespace PropSeekr.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260828000100_AddListingDetailsAndMedia")]
public partial class AddListingDetailsAndMedia : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS listing_details (
                listing_id integer PRIMARY KEY,
                details_json jsonb NOT NULL DEFAULT '{}'::jsonb,
                photo_sharing_preference character varying(30) NULL,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL
            );

            CREATE TABLE IF NOT EXISTS listing_media (
                media_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                listing_id integer NOT NULL,
                media_type character varying(20) NOT NULL,
                storage_path character varying(500) NOT NULL,
                original_file_name character varying(255) NULL,
                mime_type character varying(100) NOT NULL,
                file_size_bytes bigint NOT NULL,
                sort_order integer NOT NULL DEFAULT 0,
                created_at timestamp with time zone NOT NULL
            );

            CREATE INDEX IF NOT EXISTS ix_listing_media_listing_id_sort_order
                ON listing_media (listing_id, sort_order);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP TABLE IF EXISTS listing_media;
            DROP TABLE IF EXISTS listing_details;
            """);
    }
}
