using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PropSeekr.Data;

#nullable disable

namespace PropSeekr.Migrations;

/// <summary>
/// Restores the minimal legacy schema contracts used by the WhatsApp file
/// processor when resolving brokers and master localities.
/// </summary>
[DbContext(typeof(AppDbContext))]
[Migration("20260830094500_RestoreFileProcessorSchemaContracts")]
public partial class RestoreFileProcessorSchemaContracts : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS ux_brokers_phone_number
                ON brokers (phone_number);

            ALTER TABLE master
                ADD COLUMN IF NOT EXISTS aliases text;

            ALTER TABLE master
                ALTER COLUMN masterid ADD GENERATED BY DEFAULT AS IDENTITY;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            ALTER TABLE master
                ALTER COLUMN masterid DROP IDENTITY IF EXISTS;

            ALTER TABLE master
                DROP COLUMN IF EXISTS aliases;

            DROP INDEX IF EXISTS ux_brokers_phone_number;
            """);
    }
}
