-- Disposable schema for local mobile/API end-to-end testing only.
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TABLE brokers (
  brokerid integer PRIMARY KEY,
  phone_number text NOT NULL,
  name text,
  response_score numeric,
  status text,
  created_at timestamptz,
  last_active_at timestamptz,
  confirmation_compliance_rate numeric NOT NULL DEFAULT 100,
  visibility_penalty_flag boolean NOT NULL DEFAULT false,
  visibility_penalty_expires_at timestamptz,
  locality text,
  brokerage_name text
);

CREATE TABLE "Users" (
  "Id" uuid PRIMARY KEY,
  "BrokerId" integer,
  "Name" text NOT NULL,
  "MobileNumber" text NOT NULL,
  "Email" text,
  "PasswordHash" text NOT NULL,
  "AddressLine1" text,
  "AddressLine2" text,
  "City" text,
  "State" text,
  "Pincode" text,
  "AadharNumber" text NOT NULL,
  "PanCard" text NOT NULL,
  "GSTNumber" text,
  "ReraRegistrationNumber" text,
  "ProfilePhotoUrl" text,
  "IsMobileVerified" boolean NOT NULL DEFAULT true,
  "IsEmailVerified" boolean NOT NULL DEFAULT true,
  "CreatedDate" timestamptz NOT NULL,
  "ModifiedDate" timestamptz NOT NULL
);

CREATE TABLE listings (
  listingid integer PRIMARY KEY,
  broker_id integer NOT NULL,
  master_id integer,
  source text,
  raw_message_text text,
  listing_type text,
  property_type text,
  configuration text,
  price numeric,
  price_unit text,
  size numeric,
  furnishing text,
  facing text,
  floor_number integer,
  status text,
  expires_at timestamptz,
  last_refreshed_at timestamptz,
  last_confirmed_at timestamptz,
  freshness_score integer,
  freshness_category text,
  freshness_updated_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz,
  project_name text,
  road_info text,
  content_hash text,
  group_name text,
  message_datetime timestamptz,
  price_status text,
  city text,
  posted_by text
);

CREATE TABLE requirements (
  requirementid integer PRIMARY KEY,
  broker_id integer NOT NULL,
  source text,
  raw_message_text text,
  requirement_type text NOT NULL,
  property_type text,
  configurations text[],
  preferred_locality_ids integer[],
  budget numeric,
  budget_unit text,
  size numeric,
  furnishing_pref text,
  facing_pref text,
  status text,
  expires_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz,
  content_hash text,
  group_name text,
  message_datetime timestamptz,
  budget_type text,
  last_confirmed_at timestamptz,
  freshness_score integer,
  freshness_category text,
  freshness_updated_at timestamptz,
  city text,
  posted_by text
);

CREATE TABLE matches (
  matchid integer PRIMARY KEY,
  listing_id integer NOT NULL,
  requirement_id integer NOT NULL,
  listing_broker_id integer NOT NULL,
  requirement_broker_id integer NOT NULL,
  match_score numeric,
  status text,
  state text NOT NULL DEFAULT 'matched',
  created_at timestamptz,
  status_updated_at timestamptz,
  ai_status text,
  ai_confidence_pct numeric,
  ai_reasoning text,
  ai_flags jsonb,
  ai_validated_at timestamptz
);

CREATE TABLE match_confirmations (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id integer NOT NULL,
  broker_id integer NOT NULL,
  availability_confirmed boolean,
  price_valid boolean,
  price_negotiable boolean,
  ready_to_connect boolean,
  confirmed_at timestamptz,
  window_expires_at timestamptz,
  created_at timestamptz NOT NULL,
  UNIQUE (match_id, broker_id)
);

CREATE TABLE match_connection_requests (
  request_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id integer NOT NULL,
  requesting_broker_id integer NOT NULL,
  receiving_broker_id integer NOT NULL,
  status varchar(30) NOT NULL,
  delivery_channel varchar(20) NOT NULL,
  delivery_status varchar(30) NOT NULL,
  rejection_reason_code varchar(50),
  rejection_reason_text text,
  created_at timestamptz NOT NULL,
  responded_at timestamptz,
  expires_at timestamptz NOT NULL
);

CREATE INDEX ix_match_connection_requests_match_id_status
  ON match_connection_requests (match_id, status);
CREATE INDEX ix_match_connection_requests_receiving_broker_id_status
  ON match_connection_requests (receiving_broker_id, status);

CREATE TABLE reveals (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id integer NOT NULL UNIQUE,
  revealed_at timestamptz NOT NULL
);

CREATE TABLE credit_wallets (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  broker_id integer NOT NULL UNIQUE,
  free_credits_balance integer NOT NULL,
  paid_credits_balance integer NOT NULL,
  free_credits_reset_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE credit_transactions (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  broker_id integer NOT NULL,
  "Type" text NOT NULL,
  "Amount" integer NOT NULL,
  balance_after integer NOT NULL,
  reference_type text,
  reference_id bigint,
  reference_key varchar(100),
  "Notes" text,
  "CreatedAt" timestamptz NOT NULL
);

CREATE UNIQUE INDEX ix_credit_transactions_payment_reference
  ON credit_transactions (broker_id, reference_type, reference_key)
  WHERE reference_key IS NOT NULL;

CREATE TABLE notifications (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  broker_id integer NOT NULL,
  connection_request_id bigint,
  "Type" varchar(50) NOT NULL,
  "Channel" varchar(20) NOT NULL,
  payload jsonb,
  channel_status varchar(20) NOT NULL,
  read_at timestamptz,
  created_at timestamptz NOT NULL
);

CREATE INDEX ix_notifications_connection_request_id ON notifications (connection_request_id);

INSERT INTO brokers (brokerid, phone_number, name, status, confirmation_compliance_rate, visibility_penalty_flag, locality, brokerage_name)
VALUES
  (1, '+919111111111', 'Broker One', 'active', 100, false, 'Vijay Nagar', 'E2E Realty One'),
  (2, '+919222222222', 'Broker Two', 'active', 100, false, 'Vijay Nagar', 'E2E Realty Two');

INSERT INTO "Users" (
  "Id", "BrokerId", "Name", "MobileNumber", "Email", "PasswordHash",
  "AadharNumber", "PanCard", "IsMobileVerified", "IsEmailVerified",
  "CreatedDate", "ModifiedDate")
VALUES
  ('11111111-1111-1111-1111-111111111111', 1, 'Broker One', '9111111111', 'broker1@example.test',
   'PBKDF2-SHA256$100000$UHJvcFNlZWtyRTJFU2FsdA==$OJCpqtZCd360mSxCrEJef7vaV0L/hD3wGSkke8NExhg=',
   '111111111111', 'AAAAA1111A', true, true, NOW(), NOW()),
  ('22222222-2222-2222-2222-222222222222', 2, 'Broker Two', '9222222222', 'broker2@example.test',
   'PBKDF2-SHA256$100000$UHJvcFNlZWtyRTJFU2FsdA==$OJCpqtZCd360mSxCrEJef7vaV0L/hD3wGSkke8NExhg=',
   '222222222222', 'BBBBB2222B', true, true, NOW(), NOW());

INSERT INTO listings (
  listingid, broker_id, listing_type, property_type, configuration, price,
  price_unit, size, status, project_name, city, created_at, raw_message_text)
VALUES
  (10, 1, 'SALE', 'Flat/Apartment', '2 BHK', 5500000, 'INR', 1100,
   'active', 'E2E Heights, Vijay Nagar', 'Indore', NOW(), '2 BHK available for sale');

INSERT INTO requirements (
  requirementid, broker_id, requirement_type, property_type, configurations,
  budget, budget_unit, size, status, city, created_at, raw_message_text)
VALUES
  (20, 2, 'BUY', 'Flat/Apartment', ARRAY['2 BHK'], 6000000, 'INR', 1000,
   'active', 'Indore', NOW(), 'Client needs a 2 BHK apartment');

INSERT INTO matches (
  matchid, listing_id, requirement_id, listing_broker_id, requirement_broker_id,
  match_score, status, state, created_at, status_updated_at)
VALUES (500, 10, 20, 1, 2, 95, 'matched', 'matched', NOW(), NOW());

INSERT INTO credit_wallets (
  "Id", broker_id, free_credits_balance, paid_credits_balance, created_at, updated_at)
VALUES
  (1, 1, 10, 0, NOW(), NOW()),
  (2, 2, 10, 0, NOW(), NOW());
